### ISSUE TITLE
Circular reference in `Markdown` and `AttributedStringRenderer` classes

### ISSUE THREAD

**Issue by bbrk24** [chojnac/Dumpling#8]
There are two issues that lead to memory leaks when using Dumpling.

Every time `renderAttributedString(theme:)` is called, it allocates a new instance of `AttributedStringRenderer`, which is never deallocated. `AttributedStringRenderer.contentRenderer.renderer` is a strong reference to the `AttributedStringRenderer` instance itself, which should be `weak` or `unowned` to avoid a retain cycle.

Secondly, `Markdown` references itself through a long chain of closures:
<img width="913" alt="Screen Shot 2022-02-08 at 10 17 37 AM" src="https://user-images.githubusercontent.com/25109429/153017051-f374bb8f-48a3-4990-81d5-2258eda8685e.png">

**Comment by chojnac** [comment]
Hey, thanks for reporting that. I will investigate it.
